### ISSUE TITLE
Add [GP]GPU support

### ISSUE THREAD

**Issue by windreamer** [douban/tfmesos#1]
cf: https://github.com/tensorflow/tensorflow/issues/1996#issuecomment-211549796

@bhack :
> I think that the docker image could be based on
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/README.md. 
> Expecially if we want to have GPU support
> http://www.nvidia.com/object/apache-mesos.html and https://mesosphere.com/blog/2015/11/10/mesos-nvidia-gpus/
> See also NVIDIA/nvidia-docker#60.

Also, `tfmesos` need to allocate and isolate [GP]GPU resources.

**Comment by bhack** [comment]
See also some "nvidia" option at https://github.com/apache/mesos/blob/master/docs/configuration.md

**Comment by bhack** [comment]
We need to think how we want to handle the auto op device placement in TF. This could be overrided but we need to find some good default for data and model parallel cases because users could frequently have few GPU resource in the cluster and many CPU

**Comment by windreamer** [comment]
yeah, auto device placement is a bit annoying in TF. TF offers a context named `tf.train.replica_device_setter` which place variables to ps devices in round-robin manner. but considering GPU resources this is still not ideal.

no idea how TF team is going to solve this problem.

**Comment by bhack** [comment]
Can you formulate a comment on this on the original TF ticket?  So we can collect a comment from mrry of the TF team.

**Comment by windreamer** [comment]
OK, 

this is definitely a huge pain cosidering my poor English :( 
anyway the issue is on the way :)

**Comment by bhack** [comment]
Don't worry.. Seems good for me. It is just a technical discussion :smile:

**Comment by windreamer** [comment]
https://github.com/tensorflow/tensorflow/issues/2126

**Comment by bhack** [comment]
For GPU docker images we need to run preferably nvidia-docker command instead of docker on mesos slaves. How can be handled this?

**Comment by windreamer** [comment]
I am still thinking of how to implement GPU support. and we do not have a GPU cluster for test right now. maybe I can submit a PR based on my **guessing** , and you can do a PR-to-PR or submit a new working RP for this?

**Comment by bhack** [comment]
Yes could be useful. We have a slave node with GPU resource so we can test and continue the discussion. /cc @lenlen @mtamburrano

**Comment by vitan** [comment]
@bhack  @windreamer  , guys, I am using a quick-win solution bypass the nvidia-docker command. What the nvidia-docker actually doing is  to create a docker volume and map it to the cuda container then. So I tell mesos/docker map  the wanted volume directly.

BTW, I have 5 GPU servers for testing. I'd like to share sth. with you guys.

**Comment by bhack** [comment]
@vitan Thank you for the feedback. Can you try the last version with nvidia-docker handling assigned GPU resources with multiple tasks? I hope that @windreamer can contribute this upstream to TF soon to attract more users but we need the help of people with multiple GPU like you to test some uses cases.

**Comment by vitan** [comment]
@bhack  I am needing more input from you, given I have no more info about you guys. So "the latest version"  is the latest TF, isn't it? and I am appreciating you if anyone give me some multiple tasks sample.

**Comment by bhack** [comment]
@lenlen Do you have any protocol of an experiment to run on 5 GPU?

**Comment by bhack** [comment]
@vitan For "last version" I mean the PR at https://github.com/douban/tfmesos/pull/3
