### ISSUE TITLE
how about to set gpus'type for set ? default only scalar?

### ISSUE THREAD

**Issue by yuandy** [douban/tfmesos#25]
how about to set gpus'type for set ? default only scalar?

**Comment by windreamer** [comment]
There're two reason why GPU resources should be scalar.

1. The major one: `Apache Mesos >= 1.0.0` use scalar as GPU resources. cf: http://mesos.apache.org/documentation/latest/gpu-support/ .
2. User should be off the burden of trying to identify the detail of GPUs. So when using `Apache Meos< 1.0.0` we transform GPU set `nvidia-docker` exposed as scalar
