### ISSUE TITLE
May you mind share this to the mesos developer mailing list

### ISSUE THREAD

**Issue by haosdent** [douban/tfmesos#26]
Hi, Dear doubaners. It is awesome to see this great framework.May you mind create a pull request to https://github.com/apache/mesos/blob/master/docs/frameworks.md ? Can create a new section `Machine Learning` in that document.

Additionally, it would be greate if you could share your experiences with the mesos community. :-)

**Comment by windreamer** [comment]
It is a great honor for us! I will PR about it later

**Comment by haosdent** [comment]
Awesome, thanks a lot!

**Comment by windreamer** [comment]
cf: https://github.com/apache/mesos/pull/182
