### ISSUE TITLE
Tensorflow 0.11.x & CUDA 8.0 Support

### ISSUE THREAD

**Issue by windreamer** [douban/tfmesos#30]
Tensorflow 0.11.0 is now in release candidate, and CUDA 8.0 will be officially supported
With CUDA 8.0 we are expecting performance boost for Nvidia Pascal GPUs, abd better support for float16, and more.

Maybe we just need to update the docker file and the `requirement.txt` for the new release

**Comment by jostep** [comment]
One suggestion: may be we should relax constraint by just setting the earliest support version, such as tensorflow >=0.11.0.

**Comment by windreamer** [comment]
hmm, reasonable

**Comment by windreamer** [comment]
we are requiring `tensorflow >= 0.8.0`
cf https://github.com/douban/tfmesos/blob/master/setup.py#L51

**Comment by jostep** [comment]
Yes. I mean in the requirement as well.

**Comment by windreamer** [comment]
OK, typically `requirements.txt` is just the output of `pip freeze`?

**Comment by jostep** [comment]
Yes, but users should also be allowed to just using pip install -r requirements to install and multiple ides like pycharm eagerly ask users to meet the requirements.

**Comment by jostep** [comment]
tensorflow is also available to be directly installed by using "pip install tensorflow. "

**Comment by windreamer** [comment]
`requirements.txt` is also the control file for building docker image and virtualenv
maybe we should rename the file or put this file elsewhere?

**Comment by jostep** [comment]
we should update the requirements now, as tf just published the 0.12 version.
