### ISSUE TITLE
scheduler select says not readable

### ISSUE THREAD

**Issue by cburdorf** [douban/tfmesos#34]
I'm trying to get your simple demo.py working,  I have mesos 1.1.0 running, but when I run the docker container, it hangs on the "cluster(" call.  after digging through the code, I found that there is a loop inside Scheduler.start where the "def readable" is always returning false on the select.  As a result it gets stuck in that infinite loop in the TFMESOSScheduler start.

Any ideas why that would be?  The master is registering the call.  
1201 15:15:24.657160  2424 http.cpp:391] HTTP POST for /master/api/v1/scheduler from 100.114.84.196:53344
I1201 15:15:24.661165  2424 master.cpp:2313] Received subscription request for HTTP framework '[tensorflow] /tmp/demo.py host1:5050'
I1201 15:15:24.661810  2424 master.cpp:2411] Subscribing framework '[tensorflow] /tmp/demo.py 100.114.84.222:5050' with checkpointing disabled and capabilities [ GPU_RESOURCES ]
I1201 15:15:24.662701  2423 hierarchical.cpp:275] Added framework 9d1e7dc2-dbcf-4a7f-bd67-2ba4dd82f695-0002

I'm running non-gpu mode.

**Comment by windreamer** [comment]
Hi, the `select` part is a mini server that tries to gather connections from all remote tasks. When all connections are ready, we will know the exact members of the tensorflow cluster and will be ready to go.

If this part is not working, you may check whether the scheduler node is accessible by remote agent node and make sure all task needed is running and all connections are successfully established

**Comment by cburdorf** [comment]
Thanks for the response.

I'm just running with one master and one agent for starters.  The master is mesos 1.1.0 running without Docker.  Then i run the tfmesos docker image.  Is that the wrong configuration? Do I need to run a mesos-agent.sh separately as well? The scheduler is locking up in the docker container.

________________________________

**Comment by windreamer** [comment]
I guess before launching tfmesos task, you can try to verify whether your Mesos cluster is working with / without Docker containerizer. Maybe this would be helpful: http://mesos.apache.org/documentation/latest/docker-containerizer/

**Comment by windreamer** [comment]
One thing to note, every task of tfmesos use one CPU and 1GB mem by default. pls make sure you get enough resources for all the tasks.

**Comment by windreamer** [comment]
fixed in f3d39ebf9b979f6720df253fe73f05e49abf5927
