### ISSUE TITLE
Executor terminated

### ISSUE THREAD

**Issue by kky210** [douban/tfmesos#44]
HI.~
I was using your project very well two weeks ago.
However, there was a problem after upgrading this version.
Below is the problem I face.

I using Mesos Version
 - mesos 1.1.0
 - cuda - 8.0
 - cudnn- 5.0

my Mesos running command 
 - master
mesos-master \
      --ip=192.168.10.9 \
      --work_dir=/var/lib/mesos \
      --log_dir=/var/lib/mesos/masterlog

 - agent
mesos-agent \
      --master=deepmaster:5050 \
      --work_dir=/var/lib/mesos \
      --log_dir=/var/lib/mesos/slavelog \
      --containerizers=docker,mesos \
      --image_providers=docker \
      --isolation="filesystem/linux,docker/runtime,cgroups/devices,gpu/nvidia" \
      --executor_environment_variables='{"LD_LIBRARY_PATH": "/usr/local/lib/"}'

Running simple Test Result
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: deepmaster
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1092] LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1093] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
2016-12-22 08:07:27,775 [INFO] [tfmesos.scheduler] Tensorflow cluster registered. ( http://deepmaster:5050/#/frameworks/7b15d5da-b786-4cae-9d28-625972f40cfc-0000 )
INFO:tfmesos.scheduler:Tensorflow cluster registered. ( http://deepmaster:5050/#/frameworks/7b15d5da-b786-4cae-9d28-625972f40cfc-0000 )
2016-12-22 08:07:32,846 [WARNING] [tfmesos.scheduler] Task failed:
<Task
  mesos_task_id=2
  addr=None
>, Executor terminated
WARNING:tfmesos.scheduler:Task failed:
<Task
  mesos_task_id=2
  addr=None
>, Executor terminated
2016-12-22 08:07:33,246 [WARNING] [tfmesos.scheduler] Task failed:
<Task
  mesos_task_id=0
  addr=None
>, Executor terminated
WARNING:tfmesos.scheduler:Task failed:
<Task
  mesos_task_id=0
  addr=None
>, Executor terminated
2016-12-22 08:07:33,548 [WARNING] [tfmesos.scheduler] Task failed:
<Task
  mesos_task_id=3
  addr=None
>, Executor terminated
WARNING:tfmesos.scheduler:Task failed:
<Task
  mesos_task_id=3
  addr=None
>, Executor terminated
2016-12-22 08:07:33,649 [WARNING] [tfmesos.scheduler] Task failed:
<Task
  mesos_task_id=1
  addr=None
>, Executor terminated
WARNING:tfmesos.scheduler:Task failed:
<Task
  mesos_task_id=1
  addr=None
>, Executor terminated

Below mesos-agent Error Log
mesos-executor: error while loading shared libraries: libmesos-1.1.0.so: cannot open shared object file: No such file or directory

I've had this problem in the past and I've added --executor_environment_variables = '{"LD_LIBRARY_PATH": "/ usr / local / lib /"} to the command.

**Comment by windreamer** [comment]
Hmmm, this seems there is something wrong with the mesos installation.
Can you verify `libmesos-1.1.0.so` is in `/usr/local/lib` or any system library path?

**Comment by kky210** [comment]
yes libmesos-1.1.0.so is in /usr/local/lib
and It worked fine with the tfmesos I used before.

I have one question
Are you saying /usr/local/lib is the docker's path or Real PATH?

**Comment by windreamer** [comment]
Real path, path in the host.
After #35, we are using Mesos Containerizer instead Docker Containerizer for mesos >= 1.0

**Comment by windreamer** [comment]
you can use `cluster( .... ,containerizer_type="Docker")` to let `tfmesos` use Docker Containerizer instead.

**Comment by kky210** [comment]
how I should use it
Can you tell me?

**Comment by windreamer** [comment]
you can contact me via wechat: tianjobs
we can go through over this with more detail in Chinese

**Comment by kky210** [comment]
Thanks windreamer
