### ISSUE TITLE
GPU resources allocated properly?

### ISSUE THREAD

**Issue by ildoonet** [douban/tfmesos#51]
https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L222-L224

I guess that tfmesos will allocate gpu resources properly if GPU Resources are offered as 'SET' not as 'Scalar', But I can't manage to happen that.

They are always offered by 'Scalar'.

**Comment by windreamer** [comment]
@ildoonet GPUs are `SCALAR` if you are using Mesos's `gpu-isolator`, and the `Set` resources are for older Mesos (< 1.0) with custom resources generated by `nvidia-docker`.

In both case GPU allocation should be OK.

**Comment by ildoonet** [comment]
@windreamer 

let's say that if you have a machine with 4 gpus and an user want to launch a tfmesos with 2 gpus.

The scheduler got an offer with 4 gpus (scalar = 4), so tfmesos will launch a task with gpu id 0, 1.
The remaining resources are 2 gpus.

Next time, an user want to launch a tfmesos with 2gpus, tasks will be launched with gpu id 0, 1 since tfmesos uses gpu indexs like https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L243.

So, two different tasks are allocated at the same gpu id(s).

**Comment by windreamer** [comment]
@ildoonet here, we will transform gpu uuids (dummy ids when resource type is scalar) back to scalar.
https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L150

**Comment by windreamer** [comment]
Of coz, this is a bit too hacky. but actually we will make it much more better when compatibility no longer needed.

**Comment by ildoonet** [comment]
@windreamer 

I mean, If there are multiple users who use tfmesos and they use docker container, are gpu uuids set properly?

Example : Machine(GPU 4), Two users launched each tfmesos with 2 gpu.
1. offer : 4gpu, 2gpu used with uuid (0, 1) ----> remaining 2gpu
2. offer : 2gpu, 2gpu used with uuid (0, 1) -----> remaining 0gpu

https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L92

**Comment by windreamer** [comment]
They will be set properly.

When you are using Mesos > 1.0 with nvidia-isolator, Mesos will keep the record of the GPU allocation, all we need is to tell how many GPUs we need, and no need to tell Mesos the UUIDs.

So for your example, what mesos should seen is:

    1. offer: 4 GPUs, 2 CPUs; used: 2 GPUs ----> remaining 2 GPUs
    2. offer: 2 GPUs, 2 CPUs; used: 2 GPUs ----> remaining 0 GPUs

And the `nvidia-isolator` ensures the two task using different GPUs

**Comment by ildoonet** [comment]
Thanks. I understand! Thanks for you kind reply.
