### ISSUE TITLE
Getting started help needed

### ISSUE THREAD

**Issue by akintsakis** [douban/tfmesos#52]
Hey there!

We are trying to set up a gpu cluster for running tensorflow jobs and your project seems very promising. We are having some issues even running the examples. Our setup is Ubuntu 16.04, running mesos master and 1 agent locally (127.0.01). We are able to run the simple example and successfully get an output of 42.

However we can't run the ps/worker example, the cpu docker run fails at:
`File "mnist_replica.py", line 46, in <module>
    import input_data`

We invoke the command as:
`docker run --rm -it -e MESOS_MASTER=127.0.0.1:5050 \
             -e http_proxy=<our_proxy_info> \
             -e https_proxy=<our_proxy_info> \
             --net=host \
             -v /nfs/mnist:/nfs/mnist \
             -v /etc/passwd:/etc/passwd:ro \
             -v /etc/group:/etc/group:ro \
             -u `id -u` \
             -w /nfs/mnist \
             tfmesos/tfmesos \
             tfrun -w 1 -s 1  \
             -V /nfs/mnist:/nfs/mnist \
             -- python mnist_replica.py \
             --ps_hosts {ps_hosts} --worker_hosts {worker_hosts} \
             --job_name {job_name} --worker_index {task_index}`

Does the data exist inside the container? Also, can you please explain, do we need to execute both the docker run for cpu and nvidia-docker run for gpu commands? Shouldn't the second also take care of the parameter servers? It's not very clear what is happening behind the scenes. When we try to execute the nvidia-docker run as:
`nvidia-docker run --rm -it -e MESOS_MASTER=localhost:5050 \
             -e http_proxy=<our_proxy_info> \
             -e https_proxy=<our_proxy_info> \
             --net=host \
             -v /home/bxa005/tfmesos/examples/mnist:/nfs/mnist \
             -v /etc/passwd:/etc/passwd:ro \
             -v /etc/group:/etc/group:ro \
             -u `id -u` \
             -w /nfs/mnist \
             tfmesos/tfmesos \
             tfrun -w 1 -s 1 -Gw 1 -- python mnist_replica.py \
             --ps_hosts {ps_hosts} --worker_hosts {worker_hosts} \
             --job_name {job_name} --worker_index {task_index}`

it fails at:
`[tfrun] Process IO 2017-04-17 16:01:53,737 Failed to process event
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 148, in read
    self._callback.process_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 226, in process_event
    self.on_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 491, in on_event
    func(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 434, in on_offers
    self, [self._dict_cls(offer) for offer in offers]
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 250, in resourceOffers
    containerizer_type=self.containerizer_type
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 135, in to_task_info
    for src, dst in iteritems(self.volumes):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'NoneType' object has no attribute 'iteritems'`

**Comment by windreamer** [comment]
Hi @akintsakis,

you need to repeat the NFS(Network File System) volumes again for `tfrun` with parameter `-V`. your command may looks like this:
```
nvidia-docker run --rm -it -e MESOS_MASTER=localhost:5050 \
    -e http_proxy=<our_proxy_info> \
    -e https_proxy=<our_proxy_info> \
    --net=host \
    -v <your NFS path>:<your work path> \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -u `id -u`\
    -w  <your work path>\
    tfmesos/tfmesos \
    tfrun -w 1 -s 1 -Gw 1 -- python mnist_replica.py \
    -V <your NFS path>:<your work path> \
    --ps_hosts {ps_hosts} --worker_hosts {worker_hosts} \
    --job_name {job_name} --worker_index {task_index}     
```

Note: A network filesystem is required  for distributed training. Your training scripts should be on this NFS path and shared among the cluster.

**Comment by akintsakis** [comment]
Hi @windreamer,

Thanks for your reply. I formatted the command as you mention, and I crashed again at:
`    File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 135, in to_task_info
    for src, dst in iteritems(self.volumes):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
`
I managed to overcome this by moving the -V argument before the -- python mnist_replica, right after the -Gw 1. In this case the job failed at:

`
[tfrun] Process IO 2017-04-18 13:23:16,109 Tensorflow cluster registered. ( http://127.0.0.1:5050/#/frameworks/ffb19aa3-7a8c-467c-9f68-c76f7507dcb5-0007 )
[tfrun] MainThread 2017-04-18 13:23:17,425 Device /job:ps/task:0 activated @ grpc://nvidia-work-001:34860 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "mnist_replica.py", line 46, in <module>
    import input_data
ImportError: No module named input_data
Traceback (most recent call last):
  File "/usr/local/bin/tfrun", line 100, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python mnist_replica.py  ' returned non-zero exit status 1
`
The command I invoked is:
`
nvidia-docker run --rm -it -e MESOS_MASTER=127.0.0.1:5050 \
    -e http_proxy=proxy_info \
    -e https_proxy=proxy_info \
    --net=host \
    -v /tmp/mnist:/tmp/mnist \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -u `id -u` \
    -w  /tmp/mnist \
    tfmesos/tfmesos \
    tfrun -w 1 -s 1 -Gw 1 -V /tmp/mnist:/tmp/mnist -- python mnist_replica.py \    
    --ps_hosts {ps_hosts} --worker_hosts {worker_hosts} \
    --job_name {job_name} --worker_index {task_index}  
`

In the host, directory /tmp/mnist contains mnist.py and mnist_replica.py. Where is the input_data import going to come from?

**Comment by jostep** [comment]
the input_data is actually from tensorflow. In the tf 1.0, they changed to use read_data_sets. Could you try removing the import input_data? It should be working as well.

**Comment by akintsakis** [comment]
I removed the input_data, it works now, however, I get the warning:
`[tfrun] Process IO 2017-04-18 17:24:16,271 Tensorflow cluster registered. ( http://127.0.0.1:5050/#/frameworks/863fa5f1-cb94-4975-8eca-c6f06afb03cf-0002 )
[tfrun] MainThread 2017-04-18 17:24:17,819 Device /job:ps/task:0 activated @ grpc://nvidia-work-001:41597 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
`
Does cuDNN exist in the tfmesos container? Is this an issue?

The GPUs are being utilized, but I believe there is something wrong with the allocation of resources. When I use tfrun with arguments -w 1 -s 1 -Gw 1, in the mesos web UI, I see that in the agent there is 1 cpu allocated and 1GB of ram, as expected, but 0 gpus out of 4. When I run nvidia-smi on the host I see a python process (I assume tensorflow) on ALL 4 gpus, using max memory one each. It locks them all down. During the training steps (I set them to 20000), I actually see gpu 0 being utilized (5%) and getting hot, via nvidia-smi on the host. The other 3 gpus are idle, although their memory is reserved and occupied. Mesos UI still says 0/4 gpus allocated.

If I use two workers, -w 2 -s 1 -Gw 1, then in mesos UI I see 1/4 gpus allocated. In nvidia-smi on host I see again all gpus having memory reserved and an extra process running on gpu 0. During training steps again only gpu 0 is utilized and after a few steps it crashed with a connection timed out error, I assume some kind of communication error between workers and or the ps.

**Comment by windreamer** [comment]
@akintsakis for `tfrun`, `worker 0` will be launched locally. So with `-w 1 -s 1` there will be only the `ps:0` launched on mesos. with `-w 2 -s 1` there will be 1 ps and 1 worker launched on mesos.

**Comment by akintsakis** [comment]
@windreamer That is interesting. Can you please explain why does worker 0 run locally? If worker 0 uses a gpu, isn't that confusing regarding the resource allocation? What if mesos tries to allocate another worker to the same gpu?

**Comment by windreamer** [comment]
Ah, of course , `worker 0` can be launched remotely. Yet this is not implemented not ony due to my laziness :p, but also because it is a bit complicated to implement as `worker 0` is a bit special: the output of this worker should be displayed locally. It needs some work to bring stdout and/or stderr back via network. And also we need tensorflow logs for tensorboard 

Typically we can use `mesos-execute`, Marathon or something like this to launch tfrun itself in Mesos cluster. Or we can modify the tensorflow code to let worker 0 do no training at all and only supervise the cluster and logging for tensorboard

**Comment by windreamer** [comment]
I think we can finally make worker 0 become a remote worker. But unfortunately not now. I may find some spare time to fix it up in the future. And any contribution is welcome.

**Comment by windreamer** [comment]
@akintsakis worker 0 should be launched in Mesos now. ref: #63
