### ISSUE TITLE
TF build-in cluster VS TF-on-Mesos

### ISSUE THREAD

**Issue by vitan** [douban/tfmesos#6]
what's your guys opinions about the 2 cluster solution? @windreamer  @bhack

**Comment by windreamer** [comment]
if i'm not wrong, the build-in cluster solution of TF is based on Kubernetes? using mesos instead is apparently better for us, as we have been using mesos for a long time and a lot of out infrastructures are mesos-based.

actrually, k8s or mesos is not the core problem, as any cluster solution should be Docker-based, and what really matters is how Docker isolate and use the given resources.

**Comment by vitan** [comment]
not yet. The build-in solution is independent with mesos or K8S. I have not deep the `tfmesos` yet but we can consider 

```
`TF-build-in cluster` on `tfmesos` on `mesos`
```

solution, which can follow the TF upstream better.

**Comment by vitan** [comment]
just FYI. http://www.kdnuggets.com/2016/03/distributed-tensorflow-arrived.html

**Comment by windreamer** [comment]
@vitan what you mentioned above is just an agent for distributed training. in fact, `tfmesos` is using the same agent as what you called `TF-build-in cluster`
cf: https://github.com/douban/tfmesos/blob/master/tfmesos/server.py#L46

what `tfmesos` try to solve is all the resources should be **dynamically** allocated on demand, and multiple different training can share the same large resource pool and run **at the same time**.

for original `TensorfFlow`, k8s is the preferred way, you can find example here:
cf: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/scripts/create_tf_cluster.sh#L141

**Comment by vitan** [comment]
@windreamer  Got it and thanks for your reply.
BTW, we can keep in touch over wechat if possible.

**Comment by windreamer** [comment]
@vitan sure wechat: tianjobs
