### ISSUE TITLE
does it work on dcos-docker?

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [douban/tfmesos#61]

**Comment by windreamer** [comment]
Sorry, we have not tested it on DC/OS.

**Comment by LuisMoralesAlonso** [comment]
Trying it now... Get these errors with the basic sample plus.py (the same in all tasks):

WARNING:tfmesos.scheduler:Task failed: 
<Task
  mesos_task_id=3
  addr=None
>, Failed to launch container: Collect failed: Subprocess 'tar, tar, -x, -f, /var/lib/mesos/slave/store/docker/staging/i948lI/sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff, -C, /var/lib/mesos/slave/store/docker/staging/i948lI/8070fdcb4dff4cf605281ef5f81141484204d64280d303c5395e3fbe8cbec950/rootfs' failed: tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease: Cannot open: Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_InRelease: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_main_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial_restricted_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.lock: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.partial: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_InRelease: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_main_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: var/lib/apt/lists/.wh.security.ubuntu.com_ubuntu_dists_xenial-security_restricted_i18n_Translation-en: Cannot hard link to `var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease': Operation not permitted
tar: Exiting with failure status due to previous errors

Any idea?

**Comment by LuisMoralesAlonso** [comment]
all tasks before failing in STAGING state.
![seleccion_019](https://cloud.githubusercontent.com/assets/2943577/25661523/483ab9b2-3011-11e7-8417-b972b57c382a.png)

**Comment by windreamer** [comment]
Seems you are using unified containerizer with copy/bind backend? Using overlay backend works for us. And it is better to use Mesos >= 1.2.0

**Comment by LuisMoralesAlonso** [comment]
Mesos 1.2.1 (and DC/OS 1.9 on top).
launching DC/OS as docker containers, and plus.py with tfmesos/tfmesos from the host machine.

i'll investigate what you say about overlay...

**Comment by LuisMoralesAlonso** [comment]
Updated to overlayfs, still fails... with slightly different messages.

2017-05-03 18:14:26,155 [WARNING] [tfmesos.scheduler] Task failed: 
<Task
  mesos_task_id=0
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/9afdbea0-7608-483e-a30f-20629a1725dc/backends/aufs/rootfses/b3e2ffc5-380f-4ef2-b1db-ad7c44473c25' with aufs: Invalid argument
WARNING:tfmesos.scheduler:Task failed: 
<Task
  mesos_task_id=0
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/9afdbea0-7608-483e-a30f-20629a1725dc/backends/aufs/rootfses/b3e2ffc5-380f-4ef2-b1db-ad7c44473c25' with aufs: Invalid argument
2017-05-03 18:14:26,160 [WARNING] [tfmesos.scheduler] Task failed: 
<Task
  mesos_task_id=1
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/00060055-78da-43cf-9891-8c7e01c8ce2c/backends/aufs/rootfses/ef2f7960-fc6c-469c-9893-333886c6da5c' with aufs: Invalid argument
WARNING:tfmesos.scheduler:Task failed: 
<Task
  mesos_task_id=1
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/00060055-78da-43cf-9891-8c7e01c8ce2c/backends/aufs/rootfses/ef2f7960-fc6c-469c-9893-333886c6da5c' with aufs: Invalid argument
2017-05-03 18:14:26,161 [WARNING] [tfmesos.scheduler] Task failed: 
<Task
  mesos_task_id=2
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/3b15a7cf-0d0c-4634-bc0d-2c30f438344c/backends/aufs/rootfses/0d5715ac-561f-4825-bb35-7dbff3cb69fc' with aufs: Invalid argument
WARNING:tfmesos.scheduler:Task failed: 
<Task
  mesos_task_id=2
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/3b15a7cf-0d0c-4634-bc0d-2c30f438344c/backends/aufs/rootfses/0d5715ac-561f-4825-bb35-7dbff3cb69fc' with aufs: Invalid argument
2017-05-03 18:14:26,162 [WARNING] [tfmesos.scheduler] Task failed: 
<Task
  mesos_task_id=3
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/0a846854-efff-4a34-ab5c-af5ee790be9c/backends/aufs/rootfses/7fcbd48a-61d0-43eb-bbe9-369adbee3183' with aufs: Invalid argument
WARNING:tfmesos.scheduler:Task failed: 
<Task
  mesos_task_id=3
  addr=None
>, Failed to launch container: Failed to mount rootfs '/var/lib/mesos/slave/provisioner/containers/0a846854-efff-4a34-ab5c-af5ee790be9c/backends/aufs/rootfses/7fcbd48a-61d0-43eb-bbe9-369adbee3183' with aufs: Invalid argument

**Comment by LuisMoralesAlonso** [comment]
i've changed to overlay in docker installations, at the host and inside the mesos-agent container

**Comment by LuisMoralesAlonso** [comment]
I can run the tfmesos/tfmesos docker image from inside the mesos-agent (itself running as a docker). Any suggestion?

**Comment by LuisMoralesAlonso** [comment]
if using universal conteinarizer... how can i change it?
