### ISSUE TITLE
TFMesosScheduler hangs when a sub task failed to launch

### ISSUE THREAD

**Issue by gengmao** [douban/tfmesos#64]
Somehow a sub task failed to launch by unexpected registry issue
```
[tfrun] Process IO 2017-05-16 18:58:09,864 Tensorflow cluster registered. ( http://master.mesos:5050/#/frameworks/e46643c7-87ec-4929-b4dc-e6d694066102-0110 )
[tfrun] Process IO 2017-05-16 18:58:13,823 Task failed: 
<Task
  mesos_task_id=10
  addr=None
>, Failed to launch container: Failed to run 'docker -H unix:///var/run/docker.sock pull xxx': exited with status 1; stderr='error pulling image configuration: received unexpected HTTP status: 503 Service Unavailable
'
```
Tfrun hangs at that case. Strace shows it stuck in a loop of select calls. 
```
select(5, [4], [], [], {0, 68058})      = 0 (Timeout)
select(5, [4], [], [], {0, 100000})     = 0 (Timeout)
select(5, [4], [], [], {0, 100000})     = 0 (Timeout)
```
Seems the code is at https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L319. TFMesosScheduler keeps waiting forever for the failed task. Other tasks have connected, but as `self._start_tf_cluster()` was not reached yet, they were waiting there indefinitely too.

In this case, does it make sense to invoke `self.stop()` when `statusUpdate()` received a task failure? Similarly, should `slaveLost()`, `executorLost()` and `error()` stop driver too?

**Comment by windreamer** [comment]
This is wired. It should throw according to https://github.com/douban/tfmesos/blob/master/tfmesos/scheduler.py#L359 .
Although it is an exception in callback thread, pymesos should propagate the exception to main thread. And the program should stop.

**Comment by windreamer** [comment]
Closed due to long time inactivation.

**Comment by treadstone90** [comment]
@windreamer seeing this issue as well. when `self.started` is False then `TFMesosScheduler`is going to loop forever declining job offers. When you `reviveOffer` , mesos will start sending offers. But in the `resourceOffers` method, since task.offered is `True` for all tasks, we will simply keep suppressing offers and never exit.

**Comment by treadstone90** [comment]
Happy to submit a patch for the above, once we can figure out how to handle this.

**Comment by windreamer** [comment]
@treadstone90 expecting yout PR! :)
