### ISSUE TITLE
/job:worker/task:0's stdout seems is forwarded to tfrun driver 

### ISSUE THREAD

**Issue by gengmao** [douban/tfmesos#66]
I saw tfrun spawn a `/job:worker/task:0` task now, however, it logs nothing in stdout. The logs of it actually shows in the driver's stdout. 

Is it expected?

**Comment by windreamer** [comment]
Yeah, it is a feature. We think it is more convenient to be able to get the log from the stdout from the console of tfrun. But any suggestion is welcome.

**Comment by gengmao** [comment]
@windreamer Make sense. Can we get logs from all tasks and print them in tfrun with task ids as prefix? Do you think duplicate logs in both tasks and tfrun is ok?

**Comment by windreamer** [comment]
Hmm, technically, yes we can. But is it really necessary to bring all the logs of workers back? Can I know in which case the logs from workers that not the master is needed?

And yes we'd better replicate the log and keep one copy in sandbox. I think I may fix the replication issue in the near future.

**Comment by jostep** [comment]
I do think it is necessary for logs to be forwarded in the driver's stdout. At least we should have an option for that.
