### ISSUE TITLE
Problem running simple Test code

### ISSUE THREAD

**Issue by YuxinxinChen** [douban/tfmesos#75]
When I run:
$ docker run -e MESOS_MASTER=mesos-master:5050 \
    -e DOCKER_IMAGE=tfmesos/tfmesos \
    --net=host \
    -v /path-to-your-tfmesos-code/tfmesos/examples/plus.py:/tmp/plus.py \
    --rm \
    -it \
    tfmesos/tfmesos \
    python /tmp/plus.py mesos-master:5050

I got docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/tmp/plus.py\": permission denied"

Anyone could help me?

Yuxin

**Comment by windreamer** [comment]
Can I know your detailed setup?
