### ISSUE TITLE
How can I set the gpus resource from scalar to set

### ISSUE THREAD

**Issue by daiab** [douban/tfmesos#81]
How can I set the gpus resource from scalar to set, Because if the resource type is scalar, and use localhost:3476/docker/cli?dev=gpu_id to get nvidia-gpu info, will get the same gpu info

**Comment by windreamer** [comment]
Hi @daiab ,

You need to set GPU resources as a **Custom Resource** in Mesos
[This](https://github.com/douban/tfmesos/blob/master/misc/setup-aws-g2.sh#L44) is an example setup script for AWS you can refer to.

**Comment by daiab** [comment]
Could I use this  $(curl -s localhost:3476/mesos/cli) in the command instead ?
mesos-agent  --master=192.168.1.1:5050 \
            --containerizers=mesos,docker \
            --ip=192.168.1.1 \
            --isolation="docker/runtime,filesystem/linux,cgroups/devices,gpu/nvidia" \
            --log_dir=/dir \
            --work_dir=/dir \
            --docker=/usr/bin/nvidia-docker \
            $(curl -s localhost:3476/mesos/cli)

**Comment by daiab** [comment]
and when I use this, it returns like below, a little different to the example setup script for AWS 
--attributes=gpus:eJzUlMFr2zAUxu_7K4rOVvokWbKlm-usobBB2JoxGD3IkryYutaws5QS8r_vqWNs6XIZhLU1PljW-973Pf2wd-RTGKcuDsTsyHzstmEkhohCzrgiGalX8wrX5QzIPiPzsO1cmIj5siOr1dUcdxbLFfVNY4MOkoYcHGWtUzTXeUs1FEox5nLeWuy1tJs1Ks592J4P2853VuDb99GHPjUKl3F04Wxx_fmMQQlJEO9TGlYCBlmuqrbthm7zQAyul_VVSnzxfXqMAXgZkAZglpQX1QdGDJcKH-3g7zufrJksFOAYdR_d7ZTkdRzTOEwzhknCXRyxuwSQWHUdv8U-fn14nPbQR_3yedcNtyjYZ08r9GGF-Luielpxk5FLe9f1aIhHNTnb42Y1unRmasYSjJ9pcSz4nXZH3tY1Ma3tp5CRRR8bFJqSMZ6Rj2s7Bk-MVkk8TBs7bIhROZry2rp1wGaQlweHJDjgvU-B_0SshANRaMqCV9QXklPnmaBlznPbiMZZp44i5idGrP4TYvkaEItTIoaCN6C9paAboHnhObW2UNTKRoekECEcRcxOjFg_D-IjANW_IpYvGzFvSxaE9bQovKOlYhJ_1E1DdV4KnusyMHX8K4YTI65eEWL9whHf7N_8CAAA__8M4iHL --resources=gpus:{GPU-dbbae9e5-e40c-1fc6-494f-9076611c42fa,GPU-d63c0379-1ed6-d752-cd13-8424ab3bcac6,GPU-072b09da-09b0-47d2-aa76-a5b9e20323ee,GPU-2f81e3ad-77dc-8615-49bb-94832498e166}

**Comment by windreamer** [comment]
For every host, `Nvidia Docker` will generate an UUID for each GPU, and the detailed configuration can be generated by `curl -s localhost:3476/mesos/cli`.

From your response, `--resources=gpus:{GPU-dbbae9e5-e40c-1fc6-494f-9076611c42fa,GPU-d63c0379-1ed6-d752-cd13-8424ab3bcac6,GPU-072b09da-09b0-47d2-aa76-a5b9e20323ee,GPU-2f81e3ad-77dc-8615-49bb-94832498e166}` is the UUIDs of the GPUs on your machine, and the UUIDs is a SET resource registered into Mesos.

**Comment by daiab** [comment]
方便加下微信吗？

**Comment by windreamer** [comment]
wechat: tianjobs
