### ISSUE TITLE
why do not have readme.md?

### ISSUE THREAD

**Issue by yuandy** [douban/tfmesos#9]
can you provide a reame  Tutorial?

**Comment by windreamer** [comment]
Hmm, this project is quite **experimental** .  Here is a demo tutorial : https://github.com/tensorflow/tensorflow/issues/1996#issuecomment-211310512

Please remind the API of `tfmesos` is not stable, and may be changed in future. In fact, we are trying to add a new way compatible with the Google's to launch distributed training in the near future.

**Comment by windreamer** [comment]
README is provided in #11
